version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
      - 5555:5555 # Prisma Studio
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DB_URL=${DB_URL:-postgres://postgres:postgres@db:5432/postgres?schema=public}

  db:
    image: postgres:16.2-alpine3.19
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-postgres}

volumes:
  db-data:
